//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hautte_Pet_Parlor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Cus_ID { get; set; }
        public string Cus_Fname { get; set; }
        public string Cus_Lname { get; set; }
        public string Cus_Email { get; set; }
        public string Cus_Address { get; set; }
        public string Cus_City { get; set; }
        public string Cus_Zipcode { get; set; }
        public string Cus_Phone { get; set; }
    }
}
