//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hautte_Pet_Parlor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public int Pet_ID { get; set; }
        public string Pet_Name { get; set; }
        public string Pet_Gender { get; set; }
        public int Cus_ID { get; set; }
    }
}
